server:
   port: 8081
spring:
   application:
      name: Rundeck Client
rundeck:
   authentication:
      username: j_username
      password: j_password
      endpoint: https://rundeck.hotelbeds.com/j_security_check
      successURL: https://rundeck.hotelbeds.com/
   job:
      all: https://rundeck.hotelbeds.com/api/1/projects?format=json
      any: https://rundeck.hotelbeds.com/api/14/project/{0}/jobs/export
      edit: https://rundeck.hotelbeds.com/api/14/project/{0}/jobs/import?dupeOption=update
   elementTypeBoolean:
   - enforcedvalues
   - required
   - scheduleEnabled
   - nodeFilterEditable
   - executionEnabled
   - multipleExecutions
   - preserveOrder
   elementTypeList:
   - option
   elementsToIdentify:
      job: id
      option: name
   elementsToIgnore:
      job:
      - id
      - name
      - group
   elementsToUpdate:
      job:
      - id
      - name
      - uuid
      - description
      option:
      - name
      - enforcedvalues
      - required
      - value
      - values
      - valuesUrl
   elementsToAdd:
      job:
      - executionEnabled
      - loglevel
      - nodeFilterEditable
      - multipleExecutions
      - scheduleEnabled
      - timeout
      options:
      - preserveOrder
      option:
      - name
      - enforcedvalues
      - required
      - value
      - values
      - valuesUrl
   elementsToRemove:
      option:
      - name
   elements:
      job:
      - context
      - notification
      - sequence
      context:
      - options
      options:
      - option